---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  type: NodePort
  ports:
    - name: client-port
      port: 27017
      nodePort: 27017
      protocol: TCP
  selector:
      app: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongodb
spec:
  type: NodePort
  ports:
    - name: mongo-express-port
      port: 8081
      nodePort: 8081
      protocol: TCP
  selector:
      app: mongo-express
