---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  type: NodePort
  ports:
    - name: client-port
      port: 3306
      nodePort: 3306
      protocol: TCP
  selector:
      app: mysql
