---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres
 namespace: postgres
 labels:
  app: postgres
spec:
 replicas: 1
 selector:
  matchLabels:
   app: postgres
 template:
  metadata:
   labels:
    app: postgres
  spec:
   containers:
   - name: postgres
     image: postgres
     env:
     - name: POSTGRES_PASSWORD
       value:  $POSTGRES_PASSWORD
     - name: PGDATA
       value: /var/lib/postgresql/data/pgdata
     ports:
     - containerPort: 5432
     volumeMounts:
      - name: postgres-runtime
        mountPath: /var/lib/postgresql/data/pgdata  
   volumes:
     - name: postgres-runtime
       hostPath:
        path: /db-runtime/postgres
        type: Directory
