---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  type: NodePort
  ports:
    - name: client-port
      port: 5432
      nodePort: 5432
      protocol: TCP
  selector:
      app: postgres
